apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: rebalancer
  newName: 743156738557.dkr.ecr.us-east-1.amazonaws.com/rebalancer
  newTag: 433d706f8bbad8b07bbdf0c05a6cbc07633ef45b
resources:
- ../../base
