apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
images:
- name: queuebot
  newName: 743156738557.dkr.ecr.us-east-1.amazonaws.com/queuebot
  newTag: 50897737a3f7640a591ef7b3f91d199254904998
resources:
- ../../base
