apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
images:
- name: queuebot
  newName: 743156738557.dkr.ecr.us-east-1.amazonaws.com/queuebot
  newTag: 6e5ace4f09ab117bd65cbba297a4bd969c15e49f
resources:
- ../../base
