apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
images:
- name: rebalancer
  newName: 959984261658.dkr.ecr.us-east-2.amazonaws.com/rebalancer
  newTag: 828ec446b7a59d5f1e97e9f215d291d25d7a436e
resources:
- ../../base
